### ISSUE TITLE
Allow usage of non-Windows path

### ISSUE THREAD

**Issue by MRigal** [KWB-R/kwb.abimo#13]
UNIX (Linux and Mac OS) paths is using "/" as separator, unlike Windows which uses "\\"

Unfortunately, the R package is using a "fullWinPath" function which does not handle other platform than window. For example, see https://github.com/KWB-R/kwb.abimo/blob/master/R/run_abimo.R#L53

This way, a path `input_file <- '/Users/matthieu/dev/kwb.abimo/data/abimo_input_2019.rda'` becomes `Usersmatthieudevkwb.abimodataabimo_input_2019.rda` and it fails...

**Comment by MRigal** [comment]
FYI, to belong to this point nevertheless the issues pointed in #12, I had to do build the Qt/C++ app locally and faked it as the Windows executable by creating a symlink:
`sudo ln -s /Users/matthieu/dev/abimo/src/app/app.app/Contents/MacOS/app /opt/homebrew/lib/R/4.2/site-library/kwb.abimo/extdata/abimo_v3.3.0_win64/Abimo.exe`

**Comment by hsonne** [comment]
With #14 slashes in paths are only converted to backslashes on Windows computers.
